name: publish

on:
  release:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"

      - name: Clean install using `npm ci`
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit changes to `build` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./build

      - name: Switch to `build` branch
        run: git checkout build

      - name: Publish using `npm publish`
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
